# Generated by Django 2.2 on 2019-09-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvideos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='categorys',
            new_name='category',
        ),
    ]
